### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by dugiwarc** [Zerrien/model_load_test#1]
Hi, what are the steps to run your demo?
Best regards,
George.

**Comment by Zerrien** [comment]
Wow, I'm a big scrub and didn't properly set up this repo. Only 2 years ago, too! I should've been better than that. Not even a README...

I BELIEVE it should just be a matter of `npm install` and `npx webpack` at first glance, then you'll have a bundle.js to import. Navigate to the index.html in the folder and open it in a browser, (open it locally, not like through a URL). Give me a day and I'll update this with a proper README and some `npm` scripts to make it a little better.

**Comment by dugiwarc** [comment]
Sweet, thanks!
